services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
  
  webapp:
    build: .
    ports: 
      - 8080:5000

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090